# Generated by Django 4.2.7 on 2023-12-23 18:57

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='todo'),
            preserve_default=False,
        ),
    ]
